### PR TITLE
Add validator

### PR DESCRIPTION
**Pull request by ookami-kb**
- Added validation service ready for deploying to AWS lambda or launching from CLI.
- Added result service for deploying to AWS lambda (can be used together with API Gateway).

Currently validation service validates only data and events files (I didn't find any info about payments file, current import service is not processing it as well, as far as I found).

Upload to S3 can be done manually. Later an API Gateway can be added (or an API endpoint to the current server) that will upload files to the bucket.

### CODE REVIEW

**Comment by sitina** [comment]
I have added main.sh script to execute validator inside virtualenv. @ookami-kb, can you please also extend the PR with at least one demo/test file? Thank you

**Comment by ookami-kb** [comment]
> can you please also extend the PR with at least one demo/test file

I will try to do it later this week.

**Comment by sitina** [comment]
@ookami-kb hi Kirill, any plans with finishing this up? Thank you

**Comment by ookami-kb** [comment]
Hi, sorry, but I don't think I'll have some time for this in the near future.

**Comment by sitina** [comment]
Closing as there is no progress for quite a while. If anyone wants to get this feel free to reopen this PR.

**Pull request closed without merging**
